### PR TITLE
Updates with notebooks to generate SpikeInterface figures

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 
why did you remove the whole folder  mearec_SqMEA1015um ?
I thought this repo was to make a collection of report.

**Comment by samuelgarcia** [comment]
And the mearec_SqMEA1015um was presented in Edimburg workshop.
I think this is good that all NB are kept when they have been presented puclicaly.
No ?

**Comment by alejoe91** [comment]
I can reorganize it an leave it there. Plus making a SpikeInterface-paper folder! Probably better :) I'll do it tomorrow

**Comment by colehurwitz** [comment]
We had to move a bunch of stuff around so we could tell eLife where the code is! Sorry for not letting you know Samuel.

**Pull request merged**
